//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_de_Cambio_de_estados
    {
        public int idHistorico { get; set; }
        public string Accion { get; set; }
        public string Funcionario { get; set; }
        public string Estados { get; set; }
        public System.DateTime FechaCambio { get; set; }
    }
}
